title: "极简日志 Minimal Journal"
description: "一个极简风格的个人日志博客 | A Minimalist Personal Journal Blog"
author: "woobinkim1127"
language: "zh-CN"
baseurl: ""
url: "https://woobinkim1127.github.io"
theme: minima
permalink: /:categories/:year/:month/:day/:title.html
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
show_excerpts: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "woobinkim1127"
markdown: kramdown
